### ISSUE TITLE
安装和配置文档能补充下吗？

### ISSUE THREAD

**Issue by duantianhen2014** [Qsnh/meedu#1]
您好，项目的安装和配置文档能补充下吗？现在是404，谢谢

**Comment by Qsnh** [comment]
感谢您使用，meedu现在还处于开发当中，只有等稳定版本上线后，文档才会完善 😄 不过如果真的想要体 现 meedu 的话也非常简单，meedu是基于laravel5.5开发的系统，它的安装与laravel项目的安装不会相差太多的

**Comment by duantianhen2014** [comment]
好的，已经本地测试可以了，期待稳定版

**Comment by Qsnh** [comment]
beta1版本国庆前会上线 :smile:

**Comment by duantianhen2014** [comment]
666
