### ISSUE TITLE
微服务解耦问题

### ISSUE THREAD

**Issue by lyq11** [Qsnh/meedu#100]
您好！
我看了您系统设计，除了一个问题，其他我觉得都挺很厉害。
就是：
1.系统服务的解耦，Link和Nav都要解耦变成两个服务，会不会过于复杂？
2.我看您也划分了不同的功能，但是每个模块单独注册，会不会影响性能？
期待您的回复。

**Comment by Qsnh** [comment]
1.服务的职责划分要根据自己的业务逻辑来，没有具体的标准。meedu这里其实像link，nav这样的都可以放在一个服务里面，但是这里为了清晰也就单独分开了。
2.meedu的服务注册其实就是autoload的时候加载了这个类文件，性能相较于延迟加载肯定会有影响，但是影响其实相较于laravel启动加载的那么多文件其实倒并不是很大。

**Comment by lyq11** [comment]
谢谢大佬解答，还有一个小问题。
大佬有没有考虑把部分服务常驻内存的方案？

**Comment by lyq11** [comment]
还有个问题：

**Comment by Qsnh** [comment]
1.常驻内容暂时没有考虑，在引入微服务之后，确定了服务的职责范围，做到常驻内容完全是可以的，比如说部分服务使用hyperf开发，在meedu的容器中注册，通信方式的话http，rpc都可以。
2.Service做成composer插件也是可以的。meedu的服务注册都是通过ServiceProvider注册的，只要composer插件的ServiceProvider在应用启动的时候加载并注册相关的服务就可以了。
