### ISSUE TITLE
meedu_config.json system.theme.path 路径不对。

### ISSUE THREAD

**Issue by thimper** [Qsnh/meedu#103]
1、php-fpm部署在docker[侣里，
2、nginx 在本地宿机

每次后保存生成的meedu_config.json 里system.theme.path 的路径是 宿机的路径，不是docker 窗口里路径

**Comment by Qsnh** [comment]
在docker里面执行下 `php artisan template:switch default`

**Comment by thimper** [comment]
执行
`php artisan template:switch default` 之后确实 system.theme.path是对的。
但是在后台保存就会出错，不认识那个路径。如图：
![image](https://user-images.githubusercontent.com/3387095/76289827-fb83b600-62e4-11ea-9938-7d90ea785b0d.png)
感觉好像是出在nginx那里，nginx是部署在本地宿主机，所以nginx配置的路径也是宿机的路径。
nginx 配置如下：
`
server {
    listen 8003;
    #root /usr/local/var/www/;
    charset utf-8;
    client_max_body_size 128M;
    location / {
        root  /Users/macbookpro/code/php/meedu/public;
        index index.php index.html;
        try_files $uri $uri/ /index.php?$query_string;
        #root /Users/macbookpro/code/php/pyrocms;
    }

    location ~ \.php$ {
            root  /var/www/meedu/public;
            #root  /Users/macbookpro/code/php/meedu/public;
	        fastcgi_pass   127.0.0.1:7000;
	        fastcgi_index  index.php;
	        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
            #astcgi_param  SCRIPT_FILENAME $fastcgi_script_name;
            #fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
            #fastcgi_pass "unix:/Users/macbookpro/.config/valet/valet.sock";
	        include        fastcgi_params;
	}
}
`

**Comment by twodogegg** [comment]
你好我想问下，你这后台是怎么安装的啊。我看文档上面，没有后台的安装的部分。而且访问是 404 呢。

**Comment by twodogegg** [comment]
https://github.com/Meedu/backend 找到了。
