### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by dyt5AAUI** [Qsnh/meedu#120]
给一个用户加上会员，就删除不了。已在demo中实现。
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'role_id' cannot be null (SQL: update `users` set `role_id` = ?, `users`.`updated_at` = 2020-06-11 18:55:21 where `id` = 163)
设置只是设置会员，未设置日期

**Comment by Qsnh** [comment]
已修复
