### ISSUE TITLE
课程页面打不开

### ISSUE THREAD

**Issue by uyson** [Qsnh/meedu#122]
php7.4
mysql 8
地址：/course/1
`2020-07-01 08:04:18] production.ERROR: Argument 1 passed to App\Services\Course\Services\CourseService::find() must be of the type int, string given {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to App\\Services\\Course\\Services\\CourseService::find() must be of the type int, string given at app/Services/Course/Services/CourseService.php:93)
`

**Comment by Qsnh** [comment]
更新到最新版
