### ISSUE TITLE
安装到 /install.php?step=1的时候出错

### ISSUE THREAD

**Issue by zdlmaxwell** [Qsnh/meedu#141]
返回 500 Server Error 的错误，什么原因

**Comment by inix** [comment]
> 返回 500 Server Error 的错误，什么原因

应该是权限问题

**Comment by inix** [comment]
> 返回 500 Server Error 的错误，什么原因

我也也到这个问题了。下一步 就是500

**Comment by gd4Ark** [comment]
试试在终端手动执行一下：`php artisan storage:link`

**Comment by Qsnh** [comment]
500 错误的原因比较多，如果傻瓜安装出现了500错误建议走手动安装的过程。这样出错可随时捕获错误信息。

[手动安装教程](https://www.yuque.com/meedu/fvvkbf/hhl2wk)
