### ISSUE TITLE
后台推广链接的数据不更新

### ISSUE THREAD

**Issue by hoo-ge** [Qsnh/meedu#142]
非常感谢作者开发的这套系统，体验了2天非常不错。
今天在使用的过程中发现一个问题，就是在后天添加推广链接，多次访问推广链接后，后台的访问统计数据未更新。已经启动了queue;work和schedule:run，执行后也没有任何的数据更新，看代码好像没有相应的任务。烦请指点一下，是不是配置没对，谢谢

**Comment by Qsnh** [comment]
这个数据系统是做了延迟写入的功能，也是就当访问次数达到一定的数量才会写入到数据库中。这个数量好像是10。

**Comment by Qsnh** [comment]
meedu v3.6的延迟写入数据是100，也就是访问100次才会同步到数据库，在这期间如果清除系统缓存的话会丢失数据。meedu v3.7版本将会将这个值改为20。（暂未上线-2020/12/15）
