### ISSUE TITLE
【问题】 打算部署在生产环境，需要什么样的服务器配置？

### ISSUE THREAD

**Issue by inix** [Qsnh/meedu#144]
你好：
打算部署在生产环境，目标用户量一万，高峰并发量预估 20～30人左右。
请问应该选择怎样的配置？

**Comment by Qsnh** [comment]
最低建议2h4g3m。如果数据库能独立的话是最好了。

**Comment by inix** [comment]
> 最低建议2h4g3m。如果数据库能独立的话是最好了。

好的 谢谢。
