### ISSUE TITLE
【问题】请问傻瓜安装包下载后如何安装呢？

### ISSUE THREAD

**Issue by inix** [Qsnh/meedu#148]
你好，已经看了安装文档，傻瓜安装方式还是没有理解。
已经下载了 meedu-v2.7.2.zip ，解压后是 meedu-demo. 
下一步如何操作呢？  
直接docker-compose up吗？

**Comment by Qsnh** [comment]
[MeEdu最新程序](https://www.yuque.com/meedu/kbanfm) 已经更新到 meedu v3.7.2 版本。下载后，将运行目录配置到public，然后访问：/install.php

**Comment by inix** [comment]
> [MeEdu最新程序](https://www.yuque.com/meedu/kbanfm) 已经更新到 meedu v3.7.2 版本。下载后，将运行目录配置到public，然后访问：/install.php

@Qsnh  你好，上面写错了，我下载的是最新的 v3.7.2 
然后步骤如下：
1、进入根目录，meedu-demo，运行 docker-compose up -d；
2、访问 http://192.168.41.133/install.php
3、检查通过
4、step1 设置正确，下一步报500 错误，请问如何哪里有问题呢。
5、相关配置如下：
5.1 已经确保mysql连接正常
![image](https://user-images.githubusercontent.com/2264291/103404403-59dc9680-4b8e-11eb-9529-56d08d71677f.png)

![image](https://user-images.githubusercontent.com/2264291/103404441-855f8100-4b8e-11eb-9ef1-045c240a2b45.png)

5.2 nginx的Docker的配置正常
`
server
{
    listen 80;
	# listen 443 ssl http2;
    server_name localhost;
    index index.php index.html index.htm default.php default.htm default.html;
    root /var/www/html/public;

    client_max_body_size 2m;

    #HTTP_TO_HTTPS_START
    # if ($server_port !~ 443){
    #     rewrite ^(/.*)$ https://$host$1 permanent;
    # }

    #HTTP_TO_HTTPS_END
    # ssl_certificate    /etc/nginx/ssl/fullchain.pem;
    # ssl_certificate_key    /etc/nginx/ssl/privkey.pem;
    # ssl_protocols TLSv1.1 TLSv1.2;
    # ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    # ssl_prefer_server_ciphers on;
    # ssl_session_cache shared:SSL:10m;
    # ssl_session_timeout 10m;
    # error_page 497  https://$host$request_uri;
    #SSL-END

    #REWRITE-START URL重写规则引用,修改后将导致面板设置的伪静态规则失效
    location / {
        try_files $uri $uri/ /index.php$is_args$query_string;
    }
    #REWRITE-END

    location ~ \.php$ {
        fastcgi_pass   meedu-php:9000;
        fastcgi_index  index.php;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    }

    #禁止访问的文件或目录
    location ~ ^/(\.user.ini|\.htaccess|\.git|\.svn|\.project|LICENSE|README.md)
    {
        return 404;
    }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$
    {
        expires      30d;
        error_log off;
        access_log off;
    }

    location ~ .*\.(js|css)?$
    {
        expires      12h;
        error_log off;
        access_log off;
    }
    access_log  /var/log/nginx/meedu.log;
    error_log  /var/log/nginx/meedu.error.log;
}
`
请问哪里有问题呢？

**Comment by Qsnh** [comment]
这里看不到具体的报错信息，建议走手动安装。

**Comment by Qsnh** [comment]
[meedu手动安装教程](https://www.yuque.com/meedu/fvvkbf/hhl2wk)

**Comment by inix** [comment]
> [meedu手动安装教程](https://www.yuque.com/meedu/fvvkbf/hhl2wk)

好的 我试试

**Comment by yule-sun** [comment]
同问，使用docker-compose up 之后，首页访问不了；然后访问http://127.0.0.1/install.php到连接数据库的那一步，不输入密码提示：
MeEdu安装程序
SQLSTATE[HY000] [1045] Access denied for user 'root'@'192.168.16.4' (using password: NO)

输入密码提示：
Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/public/install.php on line 228
Fatal error: require(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/public/install.php on line 228


这个问题怎么解呀？

**Comment by inix** [comment]
> 同问，使用docker-compose up 之后，首页访问不了；然后访问[http://127.0.0.1/install.php到连接数据库的那一步，不输入密码提示：](http://127.0.0.1/install.php%E5%88%B0%E8%BF%9E%E6%8E%A5%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E9%82%A3%E4%B8%80%E6%AD%A5%EF%BC%8C%E4%B8%8D%E8%BE%93%E5%85%A5%E5%AF%86%E7%A0%81%E6%8F%90%E7%A4%BA%EF%BC%9A)
> MeEdu安装程序
> SQLSTATE[HY000] [1045] Access denied for user 'root'@'192.168.16.4' (using password: NO)
> 
> 输入密码提示：
> Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/public/install.php on line 228
> Fatal error: require(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/public/install.php on line 228
> 
> 这个问题怎么解呀？

数据库确定配置正确了吗？

**Comment by Qsnh** [comment]
> 同问，使用docker-compose up 之后，首页访问不了；然后访问[http://127.0.0.1/install.php到连接数据库的那一步，不输入密码提示：](http://127.0.0.1/install.php%E5%88%B0%E8%BF%9E%E6%8E%A5%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E9%82%A3%E4%B8%80%E6%AD%A5%EF%BC%8C%E4%B8%8D%E8%BE%93%E5%85%A5%E5%AF%86%E7%A0%81%E6%8F%90%E7%A4%BA%EF%BC%9A)
> MeEdu安装程序
> SQLSTATE[HY000] [1045] Access denied for user 'root'@'192.168.16.4' (using password: NO)
> 
> 输入密码提示：
> Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/public/install.php on line 228
> Fatal error: require(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/public/install.php on line 228
> 
> 这个问题怎么解呀？

composer install --no-dev  安装下依赖

**Comment by Qsnh** [comment]
> > 同问，使用docker-compose up 之后，首页访问不了；然后访问[http://127.0.0.1/install.php到连接数据库的那一步，不输入密码提示：](http://127.0.0.1/install.php%E5%88%B0%E8%BF%9E%E6%8E%A5%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E9%82%A3%E4%B8%80%E6%AD%A5%EF%BC%8C%E4%B8%8D%E8%BE%93%E5%85%A5%E5%AF%86%E7%A0%81%E6%8F%90%E7%A4%BA%EF%BC%9A)
> > MeEdu安装程序
> > SQLSTATE[HY000] [1045] Access denied for user 'root'@'192.168.16.4' (using password: NO)
> > 输入密码提示：
> > Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/public/install.php on line 228
> > Fatal error: require(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/public/install.php on line 228
> > 这个问题怎么解呀？
> 
> 数据库确定配置正确了吗？

composer install --no-dev 安装依赖，另外数据库无法访问是因为数据库配置错了。

**Comment by inix** [comment]
> > > 同问，使用docker-compose up 之后，首页访问不了；然后访问[http://127.0.0.1/install.php到连接数据库的那一步，不输入密码提示：](http://127.0.0.1/install.php%E5%88%B0%E8%BF%9E%E6%8E%A5%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9A%84%E9%82%A3%E4%B8%80%E6%AD%A5%EF%BC%8C%E4%B8%8D%E8%BE%93%E5%85%A5%E5%AF%86%E7%A0%81%E6%8F%90%E7%A4%BA%EF%BC%9A)
> > > MeEdu安装程序
> > > SQLSTATE[HY000] [1045] Access denied for user 'root'@'192.168.16.4' (using password: NO)
> > > 输入密码提示：
> > > Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/public/install.php on line 228
> > > Fatal error: require(): Failed opening required '../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/public/install.php on line 228
> > > 这个问题怎么解呀？
> > 
> > 
> > 数据库确定配置正确了吗？
> 
> composer install --no-dev 安装依赖，另外数据库无法访问是因为数据库配置错了。

楼主考虑docker all-in-one吗 确实挺方便的。

**Comment by inix** [comment]
手动安装可以
