### ISSUE TITLE
建议Console 自定义命令使用如下规范。

### ISSUE THREAD

**Issue by twomiao** [Qsnh/meedu#149]
1. php artisan install role
2. php artisan install administrator
3. php artisan install config
4. php artisan install:lock
5. php artisan member:role:expired
6. php artisan order:success
7. php artisan order:pay:timeout

> 建议更改如下：
- php artisan meedu:install-role
- php artisan meedu:install-administrator
- php artisan meedu:install-config
- php artisan meedu:lock
- php artisan meedu-member:role-expired
- php artisan meedu-order:pay-timeout

> 优点：能够更好归类便于查找，更加规范化且直观。命令以“meedu”开头。

**Comment by Qsnh** [comment]
很好的建议。不过目前没有打算这么做。如果更改对已安装的老用户和文档都需要做相应的变化，成本较高。
