### ISSUE TITLE
宝塔面板应用商店无法搜索到 meedu

### ISSUE THREAD

**Issue by inix** [Qsnh/meedu#151]
![image](https://user-images.githubusercontent.com/2264291/104906189-56367580-59be-11eb-8f77-fbf65237f90b.png)

请问是被下架了吗？

**Comment by Qsnh** [comment]
![image](https://user-images.githubusercontent.com/12671205/104906504-c1804780-59be-11eb-808e-ff4c90fc1435.png)

**Comment by inix** [comment]
搜索功能太搞笑了  谢谢
