### ISSUE TITLE
数据表迁移，有个严重的问题希望修复。

### ISSUE THREAD

**Issue by twomiao** [Qsnh/meedu#165]
### 当前MySQL版本：Server version: 5.7.26 MySQL Community Server (GPL)

> 1. Meedu代码中存在使用事务，但是通过数据表迁移默认是MyISAM，导致事务失效！
> 2. 希望在创建数据表迁移的时候，在代码中明确指定为“innoDB”引擎。

**Comment by Qsnh** [comment]
目前未指定引擎依赖数据库的默认配置。

![image](https://user-images.githubusercontent.com/12671205/115503948-c7c9dc80-a2a9-11eb-9e7d-525c0eaf905b.png)

存储引擎指定后续版本将会添加。

**Comment by Qsnh** [comment]
meedu v4.2已优化
