### ISSUE TITLE
备案链接指向URL地址不能访问

### ISSUE THREAD

**Issue by urna** [Qsnh/meedu#179]
测试网站 ：https://vip.english.thingswell.cn/ 

备案号指向的URL应该是 https://beian.miit.gov.cn/
实际URL是 http://www.beian.miit.gov.cn/

按照备案要求，不合规。

后台管理只有修改备案号，没有修改备案地址的功能。

MeEdu版本 v3.7.2
后台版本 v3.7
内核版本 Laravel 6.18.42
PHP版本 7.2.33

**Comment by Qsnh** [comment]
这个版本的备案访问链接是老链接，也无法修改。

升级到最新版后台系统配置可自定义。

**Comment by urna** [comment]
宝塔一键安装还是3.7.2，求更新（宝塔免费版7.5.2）
