### ISSUE TITLE
手机号登录 可以配置开启/关闭

### ISSUE THREAD

**Issue by urna** [Qsnh/meedu#182]
v 4.2.1 手机号短信登录
电脑端，没有；手机端，有

希望此功能可以配置开启/关闭，为了节约成本，不想支持手机号短信登录，还是手机号+密码+找回密码，这个模式省钱。要是用户经常用短信登录，也是一笔开销

![phone](https://user-images.githubusercontent.com/6385747/124691603-a5da1080-df0e-11eb-993e-d643b1628bf3.jpg)

![pc](https://user-images.githubusercontent.com/6385747/124691701-d15cfb00-df0e-11eb-88ad-7cc533709038.png)

**Comment by Qsnh** [comment]
不考虑。
