### ISSUE TITLE
播放器在手机端，全屏不能自动横屏

### ISSUE THREAD

**Issue by urna** [Qsnh/meedu#189]
播放器在手机端，全屏不能自动横屏。

需要在手机的系统设置里打开“自动旋转”才可以。

许多其它应用的视频播放器，不需要打开“自动旋转”。点全屏后，视频如果是竖屏格式，保持原样；如果是横屏格式，会自动横屏。

**Comment by Qsnh** [comment]
当前仓库已经全是后端的 API 程序，已无前端程序代码。

**Comment by urna** [comment]
邮件已收到，通常我在1～2天内回复。如有急事，请直接电话联系 ----我的微信 haijun-data
