### ISSUE TITLE
【BUG】课程介绍样式丢失问题

### ISSUE THREAD

**Issue by weinull** [Qsnh/meedu#190]
## 问题描述
课程介绍页面与管理端中编辑好的样式不一致（只能显示文字，后端调好的格式无法正常显示，后端使用tiny编辑器）

## 初步排查
后面排查了一下是前端CSS把编辑器的样式给覆盖了，导致前端大部分样式显示不出来。

## 处理建议
1. 建议开发者把前端样式与编辑器样式分离。
2. 建议后端支持直接写Markdown源码，前端通过Markdown渲染库直接渲染展示。

**祝好！**

**Comment by Qsnh** [comment]
tailwind 重置了部分样式，课程详情页建议做成海报图的形式，效果是最好的。
