### ISSUE TITLE
H5 端无法使用

### ISSUE THREAD

**Issue by wangyan** [Qsnh/meedu#212]
部署H5 v4.6.5后，访问H5主页无任何内容，也无法登录。

开源版本是否包含H5端？

**Comment by Qsnh** [comment]
有开源的H5 [https://github.com/meedu/h5-v1](https://github.com/meedu/h5-v1)

1.首页无内容是因为没有在后台装修，系统默认是没有填充装修数据的。

2.无法登录请检查配置。如果是自行编译部署的请检查编译时是否配置了API地址；如果是下载已编译包部署的，请检查是否在部署前修改了 `index.html` 中的 API 地址。

**Comment by wangyan** [comment]
h5-v1 可用，感谢~
