### ISSUE TITLE
4.7admin端验证码不显示

### ISSUE THREAD

**Issue by AkiArasaki** [Qsnh/meedu#216]
浏览器console报错 Access to XMLHttpRequest at 'http://192.168.199.128/backend/api/v1/captcha/image' from origin 'http://192.168.199.128:88' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested 
![屏幕截图 2022-07-21 162345](https://user-images.githubusercontent.com/96545911/180308501-0f6824e9-091e-4b09-b10f-e73235a2c21c.png)

**Comment by dary123** [comment]
我也是

**Comment by dary123** [comment]
我这边是报404
