### ISSUE TITLE
install 文件需要过滤一下

### ISSUE THREAD

**Issue by iohehe** [Qsnh/meedu#217]
你好我看到项目中的intall文件中用户输入内容都没有过滤，存在一定的XSS风险。如242行的$url, 完全可以在315行逃离双引号插入并执行任意前端代码。

**Comment by Qsnh** [comment]
嗯，install.php 并未对输入做任何安全过滤，因为这个文件是在用户第一次安装的时候访问的，如果用户成功安装系统改文件将无法打开了。也就是整个应用的周期只会触发一次，而且是管理员触发，几乎没有任何第二个人可以访问改文件。
