### ISSUE TITLE
云服务器视频URL如何使用

### ISSUE THREAD

**Issue by TerryZT** [Qsnh/meedu#252]
视频上传到云服务器以后如果使用？需要安装软件获取 URL，还是随便上传到服务器的文件夹，地址复制到视频 URL 就可以了吗？操作文档没有写很清楚，麻烦你了！
![1721686108133](https://github.com/user-attachments/assets/6dd452a0-1405-4973-86b5-962c946778e2)
![1721686144062](https://github.com/user-attachments/assets/0f8420bc-0538-4ca0-bccb-17c2bb33a650)

**Comment by Qsnh** [comment]
可以正常访问的视频URL地址即可，且必须可以跨域访问。
