### ISSUE TITLE
求助啊, H5端有问题呢

### ISSUE THREAD

**Issue by suyuerun** [Qsnh/meedu#253]
首先感谢作者大大能发布开源版本给我们用
然后我按照README里的操作, 把项目跑起来了, 是在自己的虚拟机Centos7上,然后
admin   pc    api   都没问题, 唯独 H5打不开 显示 
![image](https://github.com/user-attachments/assets/4f78ce60-29e4-4e36-9770-6b4a3b55baa7)

然后 我docker ps是
![image](https://github.com/user-attachments/assets/3802ddfa-47a4-4e9f-89ec-c0c12d472cb2)
看着也没问题, 不知道问题出哪里了, 
我的运行方式就是README写的
主要是我也不知道怎么查看对应的日志, 能否告知

**Comment by Qsnh** [comment]
`docker compsoe up -d` 运行？

8200 端口对应h5端口。

**Comment by suyuerun** [comment]
感谢关注我的提问 那是我虚拟机运行的问题, 现在我用云服务器 可以了
正好询问一下, 就是项目怎么配置SSL , 和, 我怎么用docker运行 使用docker外的数据库 或者给docker内的数据库做持久化 因为我要备份数据






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Qsnh/meedu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月9日(星期五) 下午3:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Qsnh/meedu] 求助啊, H5端有问题呢 (Issue #253)





 
docker compsoe up -d 运行？
 
8200 端口对应h5端口。

**Comment by Qsnh** [comment]
- 1.docker部署如何配置SSL可以看这篇教程：https://faq.meedu.vip/doc/z7vhilVA9L#https
- 2.目前如果使用外部mysql的话需要手动修改compose.yml文件中的MYSQL的配置为外部MYSQL配置

**Comment by suyuerun** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "过去完成时"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月5日(星期天) 下午3:57
***@***.***&gt;;

主题:&nbsp;求助, meedu-4.9.14 图片储存问题



大大求助!! HELP ME!!
我按照文档配置了文件腾讯云的文件储存用来 存图片, 但是我上传了图片到了bucket里并不能正确读取到图片是为什么呢
附录 录屏和 admin api 相应时间段日志


希望大大早日回复~
