### ISSUE TITLE
求助, 后台看不到已经上传的了视频资源

### ISSUE THREAD

**Issue by suyuerun** [Qsnh/meedu#254]
认真拜读了官方的配置手册, 感觉该配置的都配置了呀, 不知道为什么能上传但是看不到已经上传了的内容 
附图: 
![meeduYunDianboSSL](https://github.com/user-attachments/assets/dd09861e-eafd-4a49-9fb2-ae6aa864455e)
<img width="733" alt="meedu可以上传" src="https://github.com/user-attachments/assets/6b767ac0-a498-4ba1-b494-f67bc409a8e9">
<img width="350" alt="meedu视频管理" src="https://github.com/user-attachments/assets/75455079-faf5-4a09-8caa-0d1cdca51241">
<img width="883" alt="meedu视频库" src="https://github.com/user-attachments/assets/e7c7fefe-0505-4612-9007-e51aa8e38174">

**Comment by suyuerun** [comment]
我记得我发过一次这个 问题的issue啊, 今天咋找不到了= =

**Comment by Qsnh** [comment]
后台视频是需要腾讯云会通过回调通知meedu的，如果你本地的测试的话不行的。

**Comment by suyuerun** [comment]
> 后台视频是需要腾讯云会通过回调通知meedu的，如果你本地的测试的话不行的。

我是在腾讯云服务器上做的, 求教具体要怎么设置呢 这个回调, 啥的, 或者有没有log可指明我哪里有问题

**Comment by Qsnh** [comment]
系统会自动配置回调地址。前提是 meedu 的后台系统配置中的网站配置中的 API 地址必须得正确且公网可访问。

**Comment by suyuerun** [comment]
滕大哥,  我进入 api的log 看到这么
2024-08-27 11:42:36] production.ERROR: App\Bus\TencentVodBus::callbackSync|腾讯云callback设置失败.错误信息:The provided credentials could not be validated. Please check your signature is correct.  {"request_id":"v1iyyJgYCPHo"}
[2024-08-27 11:42:36] production.ERROR: App\Bus\TencentVodBus::playKeySync|腾讯云的playKey设置失败.错误信息:The provided credentials could not be validated. Please check your signature is correct.  {"request_id":"v1iyyJgYCPHo"}

报错, 求问, 是我哪一步设置的有问题呢

**Comment by Qsnh** [comment]
检查腾讯云点播的 `secretId` 和 `secretKey` 的配置

**Comment by suyuerun** [comment]
![腾讯云点播无报错但是](https://github.com/user-attachments/assets/c24dd879-5b35-4396-9ebd-882e34040af0)
![可以上传](https://github.com/user-attachments/assets/41ddba19-9a2d-43fe-85f7-db6718a165a1)

**Comment by suyuerun** [comment]
<img width="600" alt="apipeizhi" src="https://github.com/user-attachments/assets/9606e059-a181-43fd-9930-848062770212">
<img width="332" alt="apitong" src="https://github.com/user-attachments/assets/3edbeba2-30b6-44be-82b4-df7c82974da8">
<img width="797" alt="视频播放配置" src="https://github.com/user-attachments/assets/8b80b15f-3f66-4631-a1ef-3a680015fdd4">
这个api看起来是没有填错的啊, 可以正常访问, 然后不清楚我在最后哪里填的域名`格式啥的对不对

**Comment by Qsnh** [comment]
API访问地址看着没问题。检查下 nginx 日志看下是否有腾讯云的回调请求
