### ISSUE TITLE
关于后台日志的IP问题

### ISSUE THREAD

**Issue by suyuerun** [Qsnh/meedu#255]
腾哥, 现在有个其他问题, 就是我通过docker部署的项目, 后天看到的 操作日志的IP地址全都是 127.0.0.1  数据库里的注册地址也都是127  
请问是我哪里配置的有问题吗
![日志的地址都是内网](https://github.com/user-attachments/assets/4bd37803-9e83-44a1-9d6e-c34fd897f22c)

**Comment by Qsnh** [comment]
需要在 env 中增加 `TRUSTED_PROXIES=*` 配置。
