### ISSUE TITLE
无法上传图片，上传失败:错误代码1-The PutObject operation requires non-empty parameter: Bucket

### ISSUE THREAD

**Issue by esncy** [Qsnh/meedu#261]
![M5OT_SQK$M2ZU`CNZJTM0JH](https://github.com/user-attachments/assets/dadf6ea7-bf60-4ec6-ad85-c332c1efa842)
![5K ZJ(XT12}YC)@XGHN_FGV](https://github.com/user-attachments/assets/7c35632b-695b-4537-80e2-2b078ac27af2)
看到前面帖子说可能是后台设置目录有/，没有哦。有没有在用的同学？

**Comment by Qsnh** [comment]
去看存储手册配置下存储服务 https://faq.meedu.vip/doc/tGl3HiKw5g

**Comment by esncy** [comment]
> 去看存储手册配置下存储服务 https://faq.meedu.vip/doc/tGl3HiKw5g

必须OSS吗，像BANNER、网站内部的图片，可以本地化吗？
