### ISSUE TITLE
点击播放按钮不能播放

### ISSUE THREAD

**Issue by javen-73** [Qsnh/meedu#31]
https://.oss-cn-shanghai.aliyuncs.com/.m3u8?Expires=1551248149&amp;OSSAccessKeyId=********&amp;Signature=*****

可能是&amp;的原因 - -。

**Comment by javen-73** [comment]
https://.oss-cn-shanghai.aliyuncs.com/.m3u8?Expires=1551248149&a m p ;OSSAccessKeyId=***_****& a m p;Signature=****_

**Comment by Qsnh** [comment]
已收到
