### ISSUE TITLE
建议 footer 长置于底部

### ISSUE THREAD

**Issue by hutaoseven** [Qsnh/meedu#34]
**建议 footer 长置于底部**
`<footer class="container-fluid" style="position:absolute; bottom:0;"></footer>`

**Comment by hutaoseven** [comment]
如果不常驻底部，会出现：[http://www.qingpingjiaoyu.com/books](http://www.qingpingjiaoyu.com/books)

**Comment by Qsnh** [comment]
这个其实没有问题，对于没有内容的栏目，建议关闭掉 😄

**Comment by hutaoseven** [comment]
内容少，也会出现此类问题吧
