### ISSUE TITLE
请问内网下如何直接上传播放本地的视频而不用使用OSS

### ISSUE THREAD

**Issue by udpsec** [Qsnh/meedu#35]
你好！
        因为主要在内网下使用，视频特殊原因不适合上传到OSS服务。在本地上传直接播放是如何来做呢，看到了后台的视频直连功能 是调用视频所在服务器位置的url来播放的吗？ 
                                                                                  谢谢。

**Comment by Qsnh** [comment]
是的，这种情况下只能选择直链了，输入视频的地址就可以了

**Comment by udpsec** [comment]
请问电子书，faq功能在新的分支下被取消了吗？根据文档安装后台是没有这功能。

**Comment by Qsnh** [comment]
是的，新版本取消了电子书和FAQ，以后meedu更加专注视频的在线点播，电子书和FAQ后面会以插件的形式丰富

**Comment by udpsec** [comment]
好的，感谢解答

**Comment by udpsec** [comment]
会员注册后点击会员中心报错，
ErrorException thrown with message "Route [member.books] not defined. (View: /www/wwwroot/meedu/resources/views/layouts/member.blade.php) (View: /www/wwwroot/meedu/resources/views/layouts/member.blade.php)"

Stacktrace:
#74 ErrorException in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:389
#73 ErrorException in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:389
#72 InvalidArgumentException in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:389
#71 Illuminate\Routing\UrlGenerator:route in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:822
#70 route in /www/wwwroot/meedu/storage/framework/views/b66f265b855b49bb9ad25b24367a707a55a194cc.php:40
#69 include in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:43
#68 Illuminate\View\Engines\PhpEngine:evaluatePath in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:59
#67 Illuminate\View\Engines\CompilerEngine:get in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/View/View.php:142
#66 Illuminate\View\View:getContents in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/View/View.php:125
#65 Illuminate\View\View:renderContents in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/View/View.php:90
#64 Illuminate\View\View:render in /www/wwwroot/meedu/storage/framework/views/8d1012e78d70612efdb8feb44569b03977cfbf9c.php:47
#63 include in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:43
#62 Illuminate\View\Engines\PhpEngine:evaluatePath in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:59
#61 Illuminate\View\Engines\CompilerEngine:get in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/View/View.php:142
#60 Illuminate\View\View:getContents in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/View/View.php:125
#59 Illuminate\View\View:renderContents in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/View/View.php:90
#58 Illuminate\View\View:render in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Http/Response.php:42
#57 Illuminate\Http\Response:setContent in /www/wwwroot/meedu/vendor/symfony/http-foundation/Response.php:202
#56 Symfony\Component\HttpFoundation\Response:__construct in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Router.php:750
#55 Illuminate\Routing\Router:toResponse in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Router.php:722
#54 Illuminate\Routing\Router:prepareResponse in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Router.php:682
#53 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#52 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/app/Http/Middleware/NavShareMiddleware.php:33
#51 App\Http\Middleware\NavShareMiddleware:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#50 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#49 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/app/Http/Middleware/UserShareMiddleware.php:32
#48 App\Http\Middleware\UserShareMiddleware:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#46 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php:41
#45 Illuminate\Routing\Middleware\SubstituteBindings:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#44 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#43 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php:43
#42 Illuminate\Auth\Middleware\Authenticate:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#41 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#40 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:75
#39 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#38 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#37 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#36 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#35 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#34 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:63
#33 Illuminate\Session\Middleware\StartSession:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#32 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#31 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#30 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#29 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#28 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:66
#27 Illuminate\Cookie\Middleware\EncryptCookies:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#26 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#25 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#24 Illuminate\Pipeline\Pipeline:then in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Router.php:684
#23 Illuminate\Routing\Router:runRouteWithinStack in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Router.php:659
#22 Illuminate\Routing\Router:runRoute in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Router.php:625
#21 Illuminate\Routing\Router:dispatchToRoute in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Router.php:614
#20 Illuminate\Routing\Router:dispatch in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:176
#19 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:30
#18 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/barryvdh/laravel-cors/src/HandleCors.php:36
#17 Barryvdh\Cors\HandleCors:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#15 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/fideloper/proxy/src/TrustProxies.php:57
#14 Fideloper\Proxy\TrustProxies:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#12 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php:31
#11 Illuminate\Foundation\Http\Middleware\TransformsRequest:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#9 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php:27
#8 Illuminate\Foundation\Http\Middleware\ValidatePostSize:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#6 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:62
#5 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:151
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php:53
#3 Illuminate\Routing\Pipeline:Illuminate\Routing\{closure} in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:104
#2 Illuminate\Pipeline\Pipeline:then in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:151
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /www/wwwroot/meedu/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:116
#0 Illuminate\Foundation\Http\Kernel:handle in /www/wwwroot/meedu/public/index.php:69
