### ISSUE TITLE
测试新版本云插件安装报错

### ISSUE THREAD

**Issue by udpsec** [Qsnh/meedu#36]
点击云插件安装能显示 已安装 到了 插件那一选项状态再看就显示安装失败，点击历史版本切换就会显示 切换版本出现错误，错误信息：symlink(): Permission denied。

**Comment by Qsnh** [comment]
可能你需要给addons目录授权下

```
chmod -R 0777 addons
```

**Comment by udpsec** [comment]
测试成功 目录权限问题。
