### ISSUE TITLE
我用了composer安装，之后如何更新成最新的代码呢？

### ISSUE THREAD

**Issue by webbill** [Qsnh/meedu#37]
我用了composer安装，之后如何更新成最新的代码呢？

**Comment by webbill** [comment]
想要同步git上的最新代码

**Comment by Qsnh** [comment]
不知道你在使用composer安装的时候有没有保留 git ，如果保留了，直接：

```
git pull origin master
```

更新之后，执行下：

```
php artisan migrate
```

应该就可以了。如果没有保存那么只有自己下载文件覆盖了。
