### ISSUE TITLE
使用阿里云的邮件服务，群发邮件meedu有bug

### ISSUE THREAD

**Issue by webbill** [Qsnh/meedu#38]
meedu/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php

这个文件的normalizeMailboxes 函数，foreach ($mailboxes as $key => $value)执行的时候，$key如果是数据库里的值，会直接用整条json作为email的addr，从而导致最后发送邮件失败。

log里我打印了信息：

[2019-03-28 11:03:40] local.INFO: eaddr valueExample
[2019-03-28 11:03:40] local.INFO: eaddr:hello@example.com
[2019-03-28 11:03:40] local.INFO: eaddr value
[2019-03-28 11:03:40] local.INFO: eaddr:{"id":1,"email":"xxxx@xxxx.com","created_at":"2019-03-22 21:00:57","updated_at":"2019-03-22 21:00:57"}
[2019-03-28 11:03:40] local.ERROR: Address in mailbox given [{"id":1,"email":"xxxx@xxxx.com","created_at":"2019-03-22 21:00:57","updated_at":"2019-03-22 21:00:57"}] does not comply with R
FC 2822, 3.6.2. {"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [{\"id\":1,\"email\":\"xxxx@xxxx.com\",\"created_at\":\"2019-03-22 21:00:57\",\"upd
ated_at\":\"2019-03-22 21:00:57\"}] does not comply with RFC 2822, 3.6.2.

**Comment by webbill** [comment]
原始代码：
protected function normalizeMailboxes(array $mailboxes)
    {
        $actualMailboxes = [];

        foreach ($mailboxes as $key => $value) {
            if (is_string($key)) {
                //key is email addr
                $address = $key;
                $name = $value;
            } else {
                $address = $value;
                $name = null;
            }
            $this->assertValidAddress($address);
            $actualMailboxes[$address] = $name;
        }
        return $actualMailboxes;
    }
修复后代码
protected function normalizeMailboxes(array $mailboxes)
    {
        $actualMailboxes = [];

        foreach ($mailboxes as $key => $value) {
            if (is_string($key)) {
                //key is email addr
                $address = $key;
                $name = $value;
            } else {
                $address = $value;
                $name = null;
            }
            /*fix email error*/
            Log::info("eaddr value:".$value." name:".$name);
            Log::info("eaddr:".$address);
            $data = json_decode($address, true);
            if (!$data){
                $addr = $address;
            }
            else { 
                $addr = $data["email"];
            }
            Log::info("eaddr_res:".$addr);
            /*end fix*/
            //$this->assertValidAddress($address);
            $this->assertValidAddress($addr);
            $actualMailboxes[$address] = $name;
        }
        return $actualMailboxes;
    }

**Comment by Qsnh** [comment]
这个，你直接修改了laravel源码了，我自己测试的时候是没有问题的，建议你检查下用法和配置，如果真的存在问题，这个需要给laravel仓库提个issue了 😄

**Comment by webbill** [comment]
meedu/app/Jobs/DispatchEmailSubscriptionJob.php
后来发现，不应该改上面的文件，应该修改这个

原函数：
public function handle()
    {
        $emails = EmailSubscription::all();
        foreach ($emails as $email) {
            dispatch(new EmailSubscriptionHandlerJob($email, $this->title, $this->content));
        }
    }

修改后验证可行
public function handle()
    {
        $emails = EmailSubscription::all();
        foreach ($emails as $email) {
            $data = json_encode($email);
            if (!$data){
                $email_addr = $email;
            }
            else{
                $email_addr = $email["email"];
            }
            dispatch(new EmailSubscriptionHandlerJob($email_addr, $this->title, $this->content));
        }
    }

**Comment by Qsnh** [comment]
明白了，写法上的疏漏，其实直接：

```php
$email->email
```

就可以了，不需要 `json_encode`。
