### ISSUE TITLE
《新加入同学》这个功能好像不好用

### ISSUE THREAD

**Issue by webbill** [Qsnh/meedu#39]
1.《新加入同学》这个功能好像不好用，点击立刻加入之后并没有提示。
2.建议对电子书、视频的浏览都加一个访问量的统计

**Comment by Qsnh** [comment]
电子书在最新版已经去掉了，视频的访问量是有统计的。新加入同学是购买的同学。

**Comment by Qsnh** [comment]
最新模板已经去掉新加入同学
