### ISSUE TITLE
后台无法手动添加会员，或者编辑会员吗？

### ISSUE THREAD

**Issue by zchking** [Qsnh/meedu#40]
后台无法手动添加会员，或者编辑会员吗？

**Comment by zchking** [comment]
后台无法编辑会员吗？

**Comment by Qsnh** [comment]
后台有添加会员的按钮

**Comment by zchking** [comment]
![image](https://user-images.githubusercontent.com/5665818/55330072-ba730700-54c2-11e9-8807-08e36e48536e.png)
这个能编辑好弄不，我对这个框架不太熟，如果好弄，我可以参与开发。

**Comment by Qsnh** [comment]
你可以尝试下
