### ISSUE TITLE
这个是什么回事？

### ISSUE THREAD

**Issue by helinyu** [Qsnh/meedu#5]
Could not find package qsnh/meedu with version dev-master in a version   
  installable using your PHP version 7.1.0.

**Comment by Qsnh** [comment]
```
"php": ">=7.1.3",
```

**Comment by helinyu** [comment]
还是不太明白，直接说说为什么创建的命令不行吧！ 怎么设置php版本？ 本人对这方面还是一个小白

**Comment by Qsnh** [comment]
你php版本低了，必须大于7.1.3版本你，切换php版本需要看你环境，这里帮不了你
