### ISSUE TITLE
编辑管理员资料的bug

### ISSUE THREAD

**Issue by anziguoer** [Qsnh/meedu#50]
文件： /app/Http/Requests/Backend/Administrator/AdministratorRequest.php
```
   public function filldata()
    {
        $data = ['name' => $this->input('name', '')];
        $this->input('password') && $data['password'] = bcrypt($this->input('password'));
        if ($this->isMethod('post')) {
            $data['email'] = $this->input('email');
        }
        return $data;
    }
```
如果编辑管理员资料的时候不填密码， 那么则会吧此管理员的密码值为空。
问题代码：`$this->input('password') && $data['password'] = bcrypt($this->input('password'));`
1. 修改密码和修改用户资料的功能分开。
2. 在此处过过滤，密码值为空则 `unsert($data['password'])`

**Comment by Qsnh** [comment]
不会的，这里只有 `$this->input('password')` 有值 `$data` 才会有 `password` 字段的

**Comment by anziguoer** [comment]
嗯， 我下午遇到了这个问题。 管理员编辑页面有password的表单， 在编辑的时候即使不填也是会有值提交的，提交的是空， 而$this->input('password') 为false的情况是表单中没有password的表单项目， 此时上面代码的逻辑是对的。
`resources/views/backend/administrator/edit.blade.php`
```
  <div class="form-group">
                    <label>密码(可选)</label>
                    <input type="password" name="password" class="form-control" placeholder="请输入密码">
                </div>
                <div class="form-group">
                    <label>请再输入一次密码(可选)</label>
                    <input type="password" name="password_confirmation" class="form-control" placeholder="请再输入一次密码">
                </div>
```

**Comment by Qsnh** [comment]
对，如果填写了就修改它的密码

**Comment by anziguoer** [comment]
不填写会密码置空。
重要的是：``` $this->input('password') && $data['password'] = bcrypt($this->input('password'));```
这代码有问题：
1. 这个代码运行的时候会转换为逻辑运算，那么在没有密码的情况下$this->input('password')就会是flase， 整个语句执行结果就是false，最后的 
```
public function filldata()
    {
        $data = ['name' => $this->input('name', '')];
        $this->input('password') && $data['password'] = bcrypt($this->input('password'));
        if ($this->isMethod('post')) {
            $data['email'] = $this->input('email');
        }
        return $data;
    }
```
返回的`$data` 里面 `$data['password']='';` 就是这样的语句。那么最后数据库的password的字段的结果就是 '' 了。

**Comment by Qsnh** [comment]
&& 的逻辑运算如果前面为false后面就不会执行的
