### ISSUE TITLE
头像和图片不显示经检验是8000端口问题，请求支援

### ISSUE THREAD

**Issue by ishangxue** [Qsnh/meedu#78]
严格按照视频教程安装了3天终于安上了（一直卡在宝塔安不上mysql），一切正常。就是在传头像和视频封面图片的时候发现图片异常，
![1](https://user-images.githubusercontent.com/36391679/71240273-acf8f800-2343-11ea-94c9-a48acbf4d2e0.png)
做的措施
1检查链如图，有8000端口，图片显示不正常

![1](https://user-images.githubusercontent.com/36391679/71240273-acf8f800-2343-11ea-94c9-a48acbf4d2e0.png)
2去掉8000端口，图片显示正常

![2](https://user-images.githubusercontent.com/36391679/71242445-f566e480-2348-11ea-8c39-0247522441a1.png)

3结论8000端口有问题
![3](https://user-images.githubusercontent.com/36391679/71242451-f9930200-2348-11ea-88d0-0c0880d4bb76.png)
4检查防火墙端口，8000已经开放
![451](https://user-images.githubusercontent.com/36391679/71242463-00ba1000-2349-11ea-8881-0a1a739aaa33.png)

5宝塔放行8000端口
![5](https://user-images.githubusercontent.com/36391679/71242555-2e9f5480-2349-11ea-96bc-06fb3efe4a55.jpg)

6检查监听端口

7检查文件地址
![6](https://user-images.githubusercontent.com/36391679/71242560-3101ae80-2349-11ea-9677-52023c39618a.jpg)
8结论  貌似8000端口没人监听呢

问题依旧，求支援

**Comment by Qsnh** [comment]
修改 .env 文件中的 APP_URL 为你的地址
