### ISSUE TITLE
后台菜单幻灯片bug

### ISSUE THREAD

**Issue by LiPengFei1989** [Qsnh/meedu#99]
向开源精神致敬~ 发现个小问题, 还望抽空指导一下...

点击幻灯片菜单会报错,  错误码为 500, 但是没有错误提示.

我追了一下源码, 发现没有定义 backend/api/v1/slider 路由,  而且我在app/Http/Controllers/Backend/Api/V1目录下也没有找到slider控制器, 请问是我安装的问题, 还是源码未完善? 

@Qsnh @git-zjx

**Comment by Qsnh** [comment]
呃，不算bug。幻灯片是即将上线的v2.2版本的功能。后台我直接给推到master分支了，但是你用的meedu是v2.1的版本。这个后面我注意下，meedu-backend的开发推到dev分支。

**Comment by LiPengFei1989** [comment]
@Qsnh 那我需要如何解决这个问题呢?

**Comment by Qsnh** [comment]
等新版发布，或者使用dev分支代码
